use libc;

#[derive(Copy, Clone)]
pub enum InstallLoc {
  DIR_USR_SBIN,
  DIR_USR_BIN,
  DIR_SBIN,
  DIR_BIN,
  DIR_ROOT,
}

pub type bb_suid_t = libc::c_uint;
pub const BB_SUID_REQUIRE: bb_suid_t = 2;
pub const BB_SUID_MAYBE: bb_suid_t = 1;
pub const BB_SUID_DROP: bb_suid_t = 0;

/*
 * Applet table generator.
 * Runs on host and produces include/applet_tables.h
 *
 * Copyright (C) 2007 Denys Vlasenko <vda.linux@googlemail.com>
 *
 * Licensed under GPLv2, see file LICENSE in this source tree.
 */

#[derive(Clone)]
#[repr(C)]
pub struct bb_applet {
  pub name: &'static str,
  pub main: &'static str,
  pub install_loc: InstallLoc,
  pub need_suid: bb_suid_t,

  /* true if instead of fork(); exec("applet"); waitpid();
   * one can do fork(); exit(applet_main(argc,argv)); waitpid(); */
  pub noexec: libc::c_uchar,

  /* Even nicer */
  /* true if instead of fork(); exec("applet"); waitpid();
   * one can simply call applet_main(argc,argv); */
  pub nofork: libc::c_uchar,
}

/* Define struct bb_applet applets[] */
pub const NUM_APPLETS: libc::c_uint = 396;

/*
 * applets.h - a listing of all busybox applets.
 *
 * If you write a new applet, you need to add an entry to this list to make
 * busybox aware of it.
 */
/*
name  - applet name as it is typed on command line
help  - applet name, converted to C (ether-wake: help = ether_wake)
main  - corresponding <applet>_main to call (bzcat: main = bunzip2)
l     - location to install link to: [/usr]/[s]bin
s     - suid type:
        BB_SUID_REQUIRE: will complain if busybox isn't suid
        and is run by non-root (applet_main() will not be called at all)
        BB_SUID_DROP: will drop suid prior to applet_main()
        BB_SUID_MAYBE: neither of the above
        (every instance of BB_SUID_REQUIRE and BB_SUID_MAYBE
        needs to be justified in comment)
        NB: please update FEATURE_SUID help text whenever you add/remove
        BB_SUID_REQUIRE or BB_SUID_MAYBE applet.
*/
pub static mut applets: [bb_applet; 396] = [
  bb_applet {
    name: "gunzip",
    main: "gunzip",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "zcat",
    main: "gunzip",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "bunzip2",
    main: "bunzip2",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "bzcat",
    main: "bunzip2",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "unlzma",
    main: "unlzma",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "lzcat",
    main: "unlzma",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "lzma",
    main: "unlzma",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "unxz",
    main: "unxz",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "xzcat",
    main: "unxz",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "xz",
    main: "unxz",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "bzip2",
    main: "bzip2",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "cpio",
    main: "cpio",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "dpkg",
    main: "dpkg",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "dpkg-deb",
    main: "dpkg_deb",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "gzip",
    main: "gzip",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "lzop",
    main: "lzop",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "rpm",
    main: "rpm",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "rpm2cpio",
    main: "rpm2cpio",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "tar",
    main: "tar",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "unzip",
    main: "unzip",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "chvt",
    main: "chvt",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "clear",
    main: "clear",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "deallocvt",
    main: "deallocvt",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "dumpkmap",
    main: "dumpkmap",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "fgconsole",
    main: "fgconsole",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "kbd_mode",
    main: "kbd_mode",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "loadfont",
    main: "loadfont",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "setfont",
    main: "setfont",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "loadkmap",
    main: "loadkmap",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "openvt",
    main: "openvt",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "reset",
    main: "reset",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "resize",
    main: "resize",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "setconsole",
    main: "setconsole",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "setkeycodes",
    main: "setkeycodes",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "setlogcons",
    main: "setlogcons",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "showkey",
    main: "showkey",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "basename",
    main: "basename",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "cat",
    main: "cat",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "chgrp",
    main: "chgrp",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "chmod",
    main: "chmod",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "chown",
    main: "chown",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "chroot",
    main: "chroot",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "cksum",
    main: "cksum",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "comm",
    main: "comm",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "cp",
    main: "cp",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "cut",
    main: "cut",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "date",
    main: "date",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "dd",
    main: "dd",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "df",
    main: "df",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "dirname",
    main: "dirname",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "dos2unix",
    main: "dos2unix",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "unix2dos",
    main: "dos2unix",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "du",
    main: "du",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "echo",
    main: "echo",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "env",
    main: "env",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "expand",
    main: "expand",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "unexpand",
    main: "expand",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "expr",
    main: "expr",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "factor",
    main: "factor",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "false",
    main: "false",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "fold",
    main: "fold",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "head",
    main: "head",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "hostid",
    main: "hostid",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "groups",
    main: "id",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "id",
    main: "id",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "install",
    main: "install",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "link",
    main: "link",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "ln",
    main: "ln",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "logname",
    main: "logname",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "ls",
    main: "ls",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "md5sum",
    main: "md5_sha1_sum",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "sha1sum",
    main: "md5_sha1_sum",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "sha3sum",
    main: "md5_sha1_sum",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "sha256sum",
    main: "md5_sha1_sum",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "sha512sum",
    main: "md5_sha1_sum",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "mkdir",
    main: "mkdir",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "mkfifo",
    main: "mkfifo",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "mknod",
    main: "mknod",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "mktemp",
    main: "mktemp",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "mv",
    main: "mv",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "nice",
    main: "nice",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "nl",
    main: "nl",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "nohup",
    main: "nohup",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "nproc",
    main: "nproc",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "od",
    main: "od",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "paste",
    main: "paste",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "printenv",
    main: "printenv",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "printf",
    main: "printf",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "pwd",
    main: "pwd",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "readlink",
    main: "readlink",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "realpath",
    main: "realpath",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "rm",
    main: "rm",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "rmdir",
    main: "rmdir",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "seq",
    main: "seq",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "shred",
    main: "shred",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "shuf",
    main: "shuf",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "sleep",
    main: "sleep",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "sort",
    main: "sort",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "split",
    main: "split",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "stat",
    main: "stat",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "stty",
    main: "stty",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "sum",
    main: "sum",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "sync",
    main: "sync",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "fsync",
    main: "fsync",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "tac",
    main: "tac",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "tail",
    main: "tail",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "tee",
    main: "tee",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "test",
    main: "test",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "[",
    main: "test",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "[[",
    main: "test",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "timeout",
    main: "timeout",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "touch",
    main: "touch",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "tr",
    main: "tr",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "true",
    main: "true",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "truncate",
    main: "truncate",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "tty",
    main: "tty",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "uname",
    main: "uname",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "arch",
    main: "uname",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "uniq",
    main: "uniq",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "unlink",
    main: "unlink",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "usleep",
    main: "usleep",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "uudecode",
    main: "uudecode",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "base64",
    main: "base64",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "uuencode",
    main: "uuencode",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "wc",
    main: "wc",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "users",
    main: "who",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "w",
    main: "who",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "who",
    main: "who",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "whoami",
    main: "whoami",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "yes",
    main: "yes",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "pipe_progress",
    main: "pipe_progress",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "run-parts",
    main: "run_parts",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "start-stop-daemon",
    main: "start_stop_daemon",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "which",
    main: "which",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "chattr",
    main: "chattr",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "fsck",
    main: "fsck",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "lsattr",
    main: "lsattr",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "awk",
    main: "awk",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "cmp",
    main: "cmp",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "diff",
    main: "diff",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "ed",
    main: "ed",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "patch",
    main: "patch",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "sed",
    main: "sed",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "vi",
    main: "vi",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "find",
    main: "find",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "grep",
    main: "grep",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "egrep",
    main: "grep",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "fgrep",
    main: "grep",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "xargs",
    main: "xargs",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "bootchartd",
    main: "bootchartd",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "halt",
    main: "halt",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "poweroff",
    main: "halt",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "reboot",
    main: "halt",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "init",
    main: "init",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "linuxrc",
    main: "init",
    install_loc: InstallLoc::DIR_ROOT,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "nuke",
    main: "nuke",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "resume",
    main: "resume",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "add-shell",
    main: "add_remove_shell",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "remove-shell",
    main: "add_remove_shell",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "addgroup",
    main: "addgroup",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "adduser",
    main: "adduser",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "chpasswd",
    main: "chpasswd",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "cryptpw",
    main: "cryptpw",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "mkpasswd",
    main: "cryptpw",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "deluser",
    main: "deluser",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "delgroup",
    main: "deluser",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "getty",
    main: "getty",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "login",
    main: "login",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_REQUIRE,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "passwd",
    main: "passwd",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_REQUIRE,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "su",
    main: "su",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_REQUIRE,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "sulogin",
    main: "sulogin",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "vlock",
    main: "vlock",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_REQUIRE,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "makemime",
    main: "makemime",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "popmaildir",
    main: "popmaildir",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "reformime",
    main: "reformime",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "sendmail",
    main: "sendmail",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "adjtimex",
    main: "adjtimex",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "bc",
    main: "bc",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "dc",
    main: "dc",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "beep",
    main: "beep",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "chat",
    main: "chat",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "conspy",
    main: "conspy",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "crond",
    main: "crond",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "crontab",
    main: "crontab",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_REQUIRE,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "devmem",
    main: "devmem",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "fbsplash",
    main: "fbsplash",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "hdparm",
    main: "hdparm",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "hexedit",
    main: "hexedit",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "i2cget",
    main: "i2cget",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "i2cset",
    main: "i2cset",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "i2cdump",
    main: "i2cdump",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "i2cdetect",
    main: "i2cdetect",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "i2ctransfer",
    main: "i2ctransfer",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "less",
    main: "less",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "lsscsi",
    main: "lsscsi",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "makedevs",
    main: "makedevs",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "man",
    main: "man",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "microcom",
    main: "microcom",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "mt",
    main: "mt",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "nandwrite",
    main: "nandwrite",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "nanddump",
    main: "nandwrite",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "partprobe",
    main: "partprobe",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "raidautorun",
    main: "raidautorun",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "readahead",
    main: "readahead",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "runlevel",
    main: "runlevel",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "rx",
    main: "rx",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "setfattr",
    main: "setfattr",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "setserial",
    main: "setserial",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "strings",
    main: "strings",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "time",
    main: "time",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "ts",
    main: "ts",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "ttysize",
    main: "ttysize",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "ubiattach",
    main: "ubi_tools",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "ubidetach",
    main: "ubi_tools",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "ubimkvol",
    main: "ubi_tools",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "ubirmvol",
    main: "ubi_tools",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "ubirsvol",
    main: "ubi_tools",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "ubiupdatevol",
    main: "ubi_tools",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "ubirename",
    main: "ubirename",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "volname",
    main: "volname",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "watchdog",
    main: "watchdog",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "modinfo",
    main: "modinfo",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "lsmod",
    main: "lsmod",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "modprobe",
    main: "modprobe",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "depmod",
    main: "modprobe",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "insmod",
    main: "modprobe",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "rmmod",
    main: "modprobe",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "arp",
    main: "arp",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "arping",
    main: "arping",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "brctl",
    main: "brctl",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "dnsd",
    main: "dnsd",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "ether-wake",
    main: "ether_wake",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "ftpd",
    main: "ftpd",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "ftpget",
    main: "ftpgetput",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "ftpput",
    main: "ftpgetput",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "dnsdomainname",
    main: "hostname",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "hostname",
    main: "hostname",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "httpd",
    main: "httpd",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "ifconfig",
    main: "ifconfig",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "ifenslave",
    main: "ifenslave",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "ifplugd",
    main: "ifplugd",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "ifup",
    main: "ifupdown",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "ifdown",
    main: "ifupdown",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "inetd",
    main: "inetd",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "ip",
    main: "ip",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "ipaddr",
    main: "ipaddr",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "iplink",
    main: "iplink",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "iproute",
    main: "iproute",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "iprule",
    main: "iprule",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "iptunnel",
    main: "iptunnel",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "ipneigh",
    main: "ipneigh",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "ipcalc",
    main: "ipcalc",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "fakeidentd",
    main: "fakeidentd",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "nameif",
    main: "nameif",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "nbd-client",
    main: "nbdclient",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "nc",
    main: "nc",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "netstat",
    main: "netstat",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "nslookup",
    main: "nslookup",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "ntpd",
    main: "ntpd",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "ping",
    main: "ping",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_MAYBE,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "ping6",
    main: "ping6",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_MAYBE,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "pscan",
    main: "pscan",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "route",
    main: "route",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "slattach",
    main: "slattach",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "ssl_client",
    main: "ssl_client",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "tc",
    main: "tc",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "tcpsvd",
    main: "tcpudpsvd",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "udpsvd",
    main: "tcpudpsvd",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "telnet",
    main: "telnet",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "telnetd",
    main: "telnetd",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "tftp",
    main: "tftp",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "tftpd",
    main: "tftpd",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "traceroute",
    main: "traceroute",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_MAYBE,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "traceroute6",
    main: "traceroute6",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_MAYBE,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "tunctl",
    main: "tunctl",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "vconfig",
    main: "vconfig",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "wget",
    main: "wget",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "whois",
    main: "whois",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "zcip",
    main: "zcip",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "lpd",
    main: "lpd",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "lpq",
    main: "lpqr",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "lpr",
    main: "lpqr",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "free",
    main: "free",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "fuser",
    main: "fuser",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "iostat",
    main: "iostat",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "kill",
    main: "kill",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "killall",
    main: "kill",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "killall5",
    main: "kill",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "lsof",
    main: "lsof",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "mpstat",
    main: "mpstat",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "nmeter",
    main: "nmeter",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "pgrep",
    main: "pgrep",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "pkill",
    main: "pgrep",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "pidof",
    main: "pidof",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "pmap",
    main: "pmap",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "powertop",
    main: "powertop",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "ps",
    main: "ps",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "pstree",
    main: "pstree",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "pwdx",
    main: "pwdx",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "smemcap",
    main: "smemcap",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "sysctl",
    main: "sysctl",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "top",
    main: "top",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "uptime",
    main: "uptime",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "watch",
    main: "watch",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "chpst",
    main: "chpst",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "envdir",
    main: "chpst",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "envuidgid",
    main: "chpst",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "setuidgid",
    main: "chpst",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "softlimit",
    main: "chpst",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "runsv",
    main: "runsv",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "runsvdir",
    main: "runsvdir",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "sv",
    main: "sv",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "svc",
    main: "svc",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "svok",
    main: "svok",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "svlogd",
    main: "svlogd",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "ash",
    main: "ash",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "sh",
    main: "ash",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "cttyhack",
    main: "cttyhack",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "hush",
    main: "hush",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "klogd",
    main: "klogd",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "logger",
    main: "logger",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "logread",
    main: "logread",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "syslogd",
    main: "syslogd",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "acpid",
    main: "acpid",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "blkdiscard",
    main: "blkdiscard",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "blkid",
    main: "blkid",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "blockdev",
    main: "blockdev",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "cal",
    main: "cal",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "chrt",
    main: "chrt",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "dmesg",
    main: "dmesg",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "eject",
    main: "eject",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "fallocate",
    main: "fallocate",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "fatattr",
    main: "fatattr",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "fbset",
    main: "fbset",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "fdformat",
    main: "fdformat",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "fdisk",
    main: "fdisk",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "findfs",
    main: "findfs",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_MAYBE,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "flock",
    main: "flock",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "fdflush",
    main: "freeramdisk",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "freeramdisk",
    main: "freeramdisk",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "fsck.minix",
    main: "fsck_minix",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "fsfreeze",
    main: "fsfreeze",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "fstrim",
    main: "fstrim",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "getopt",
    main: "getopt",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "hexdump",
    main: "hexdump",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "hd",
    main: "hexdump",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "xxd",
    main: "xxd",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "hwclock",
    main: "hwclock",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "ionice",
    main: "ionice",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "ipcrm",
    main: "ipcrm",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "ipcs",
    main: "ipcs",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "last",
    main: "last",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "losetup",
    main: "losetup",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "lspci",
    main: "lspci",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "lsusb",
    main: "lsusb",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "mdev",
    main: "mdev",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "mesg",
    main: "mesg",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "mke2fs",
    main: "mkfs_ext2",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "mkfs.ext2",
    main: "mkfs_ext2",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "mkfs.minix",
    main: "mkfs_minix",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "mkdosfs",
    main: "mkfs_vfat",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "mkfs.vfat",
    main: "mkfs_vfat",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "mkswap",
    main: "mkswap",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "more",
    main: "more",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "mount",
    main: "mount",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_MAYBE,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "mountpoint",
    main: "mountpoint",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "nologin",
    main: "scripted",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "nsenter",
    main: "nsenter",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "pivot_root",
    main: "pivot_root",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 1i32 as libc::c_uchar,
  },
  bb_applet {
    name: "rdate",
    main: "rdate",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "rdev",
    main: "rdev",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "readprofile",
    main: "readprofile",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "renice",
    main: "renice",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "rev",
    main: "rev",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "rtcwake",
    main: "rtcwake",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "script",
    main: "script",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "scriptreplay",
    main: "scriptreplay",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "setarch",
    main: "setarch",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "linux32",
    main: "setarch",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "linux64",
    main: "setarch",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "setpriv",
    main: "setpriv",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "setsid",
    main: "setsid",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "swapon",
    main: "swap_on_off",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "swapoff",
    main: "swap_on_off",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "switch_root",
    main: "switch_root",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "run-init",
    main: "switch_root",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "taskset",
    main: "taskset",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "uevent",
    main: "uevent",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "umount",
    main: "umount",
    install_loc: InstallLoc::DIR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
  bb_applet {
    name: "unshare",
    main: "unshare",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "wall",
    main: "wall",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_REQUIRE,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "udhcpc6",
    main: "udhcpc6",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "udhcpc",
    main: "udhcpc",
    install_loc: InstallLoc::DIR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "udhcpd",
    main: "udhcpd",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "dhcprelay",
    main: "dhcprelay",
    install_loc: InstallLoc::DIR_USR_SBIN,
    need_suid: BB_SUID_DROP,
    noexec: 0,
    nofork: 0,
  },
  bb_applet {
    name: "dumpleases",
    main: "dumpleases",
    install_loc: InstallLoc::DIR_USR_BIN,
    need_suid: BB_SUID_DROP,
    noexec: 1i32 as libc::c_uchar,
    nofork: 0,
  },
];
